title: portfolio Nicolas B
description: c'est le portfolio de Nicolas B.
baseline: embauchez-moi
copyright: Nicolas B.  2016
encodage: UTF-8
telephone: 0123456789
mail: nicolas.broquet@etu.univ-rouen.fr
adresse: 3 chemin de l'Ã©glise 41000 Blois
